{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress 
  namespace: {{ .Release.Namespace }}
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  tls:
  - hosts:
    - {{ .Values.app.name }}-zdmp.{{ .Values.ingress.domain }}
  rules:
  - host: {{ .Values.app.name }}-zdmp.{{ .Values.ingress.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.app.name }} 
          servicePort: 8080 
{{- end }}
