##################################################################################################
# App service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }} 
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}  
    service: {{ .Values.app.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    name: http
    targetPort: {{ .Values.app.port }} 
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodeport }}
{{- end }}
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.name }} 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }} 
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }} 
    spec:
      serviceAccountName: {{ .Values.app.name }}-serviceaccount
{{- if .Values.persistence.enabled }}
      volumes:
        - name: {{ .Values.app.name }}-pv-storage
          persistentVolumeClaim:
            claimName: {{ .Values.app.name }}-pv-claim
{{- end }}
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.version }} 
        imagePullPolicy: {{ .Values.image.pullPolicy }} 
        ports:
        - name: http 
          containerPort: {{ .Values.app.port }} 
        envFrom:
        - configMapRef:
            name: {{ .Values.app.name }}-configmap
{{- if .Values.persistence.enabled }}
        volumeMounts:
          - mountPath: {{ .Values.persistence.mountpath | quote }}
            name: {{ .Values.app.name }}-pv-storage
{{- end }}
      imagePullSecrets:
      - name: {{ .Values.image.secret }}
---
