{{- if .Values.defaultSettings.zdmp }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.secret }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "zdmp-data-harmonisation-runtime-idp.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "secret" . }}
{{- end }}
