---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.name }}-serviceaccount 
  namespace: {{ .Release.Namespace }}
#  namespace: idpruntime
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.app.name }}-rolebinding 
  namespace: {{ .Release.Namespace }}
#  namespace: idpruntime
roleRef:
  kind: ClusterRole
  name: admin 
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.app.name }}-serviceaccount 
#    namespace: idpruntime
